###
# Créer un nouvel utilisateur
POST http://localhost:3000/users/create_user
Content-Type: application/json

{
  "firm_name": "Entreprise1",
  "first_name": "Contact1",
  "last_name": "Nom1",
  "email": "contact1@example.com",
  "phone_number": "1234567890",
  "password": "motDePasse1"
}

###
# Créer un nouvel utilisateur
POST http://localhost:3000/users/create_user
Content-Type: application/json

{
  "firm_name": "Entreprise2",
  "first_name": "Contact2",
  "last_name": "Nom2",
  "email": "contact2@example.com",
  "phone_number": "9876543210",
  "password": "motDePasse2"
}

###
# Créer un nouvel utilisateur
POST http://localhost:3000/users/create_user
Content-Type: application/json

{
  "firm_name": "Entreprise3",
  "first_name": "Contact3",
  "last_name": "Nom3",
  "email": "contact3@example.com",
  "phone_number": "5551234567",
  "password": "motDePasse3"
}

###
#Mettre à jour le mot de passe d'un utilisateur existant
PUT http://localhost:3000/users/hashPassword
Content-Type: application/json

{
  "firm_name": "Entreprise5",
  "password": "newsecurepassword"
}

###
# Mettre à jour un utilisateur existant
PUT http://localhost:3000/users/update_user
Content-Type: application/json

{
  "firm_name": "Entreprise5",
  "first_name": "Contact5",
  "last_name": "Nom5",
  "email": "contact5@example.com",
  "phone_number": "1112223333"
}

###
# Supprimer un utilisateur
DELETE http://localhost:3000/users/delete_user/Entreprise2

###
# Obtenir un utilisateur par son nom d'entreprise
GET http://localhost:3000/users/get_user/Entreprise5

###
# Obtenir la liste de tous les utilisateurs
GET http://localhost:3000/users/get_all_users

###
PUT http://localhost:3000/users/update_user
Content-Type: application/json

{
  "firm_name": "Entreprise4",
  "email": "benrei@hotmail.fr"
}

###
POST http://localhost:3000/users/notify
Content-Type: application/json

{
  "firm_name": "Entreprise1"
}