###
POST http://localhost:3000/users/create_admin
Content-Type: application/json

{
  "firm_name": "admin",
  "first_name": "admin",
  "last_name": "istrateur",
  "email": "contactadmin@example.com",
  "phone_number": "0000000000",
  "password": "MDPadmin"
}

###
# Créer un nouvel utilisateur
POST http://localhost:3000/users/create_user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJtX25hbWUiOiJhZG1pbiIsImlhdCI6MTcwNTUwMDQ3MCwiZXhwIjoxNzEzMjc2NDcwfQ.DNztKCui6iIQSNCDVoQ4V8dFAz8nfq9vM8Ar3hC-pz0
Content-Type: application/json

{
  "firm_name": "Entreprise5",
  "first_name": "Contact5",
  "last_name": "Nom5",
  "email": "benrei@hotmail.fr",
  "phone_number": "1234567890"
}

###
# Créer un nouvel utilisateur
POST http://localhost:3000/users/create_user
Content-Type: application/json

{
  "firm_name": "Entreprise2",
  "first_name": "Contact2",
  "last_name": "Nom2",
  "email": "contact2@example.com",
  "phone_number": "9876543210",
  "password": "motDePasse2"
}

###
# Créer un nouvel utilisateur
POST http://localhost:3000/users/create_user
Content-Type: application/json

{
  "firm_name": "Entreprise3",
  "first_name": "Contact3",
  "last_name": "Nom3",
  "email": "contact3@example.com",
  "phone_number": "5551234567",
  "password": "motDePasse3"
}

###
#Mettre à jour le mot de passe d'un utilisateur existant
PUT http://localhost:3000/users/hashPassword
Content-Type: application/json

{
  "firm_name": "Entreprise5",
  "password": "newsecurepassword"
}

###
# Mettre à jour un utilisateur existant
PUT http://localhost:3000/users/update_user
Content-Type: application/json

{
  "firm_name": "Entreprise5",
  "first_name": "Contact5",
  "last_name": "Nom5",
  "email": "contact5@example.com",
  "phone_number": "1112223333"
}

###
# Supprimer un utilisateur
DELETE http://localhost:3000/users/delete_user/Entreprise2

###
# Obtenir un utilisateur par son nom d'entreprise
GET http://localhost:3000/users/get_user/Entreprise5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJtX25hbWUiOiJhZG1pbiIsImlhdCI6MTcwNTY3MTg3NywiZXhwIjoxNzEzNDQ3ODc3fQ.PMOGNubmucY-FSMsPE4b_AKqcMBjQriinZ8VvMqRAj0

###
# Obtenir la liste de tous les utilisateurs
GET http://localhost:3000/users/get_all_users

###
PUT http://localhost:3000/users/update_user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJtX25hbWUiOiJhZG1pbiIsImlhdCI6MTcwNTUwMDQ3MCwiZXhwIjoxNzEzMjc2NDcwfQ.DNztKCui6iIQSNCDVoQ4V8dFAz8nfq9vM8Ar3hC-pz0
Content-Type: application/json

{
  "firm_name": "Entreprise2",
  "email": "benrei@hotmail.fr",
  "generate_password": true
}

###
POST http://localhost:3000/users/notify
Content-Type: application/json

{
  "firm_name": "Entreprise1"
}

###
GET http://localhost:3000/users/get_all_firm_name
Content-Type: application/json

###
PUT http://localhost:3000/users/recup_mail?firm_name=Entreprise1
Content-Type: application/json

### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "firm_name": "admin",
    "password": "MDPadmin"
}

###
POST http://localhost:3000/auth/logout
Content-Type: application/json
