###
POST http://localhost:3000/users/create_admin
Content-Type: application/json

{
  "firm_name": "admin",
  "first_name": "admin",
  "last_name": "istrateur",
  "email": "contactadmin@example.com",
  "phone_number": "0000000000",
  "password": "MDPadmin"
}

###
# Créer un nouvel utilisateur
POST http://localhost:3000/users/create_user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJtX25hbWUiOiJhZG1pbiIsImlhdCI6MTcwNTUwMDQ3MCwiZXhwIjoxNzEzMjc2NDcwfQ.DNztKCui6iIQSNCDVoQ4V8dFAz8nfq9vM8Ar3hC-pz0
Content-Type: application/json

{
  "firm_name": "Entreprise6",
  "first_name": "Contact6",
  "last_name": "Nom6",
  "email": "benrei@hotmail.fr",
  "phone_number": "1234567891"
}

###
# Créer un nouvel utilisateur
POST http://localhost:3000/users/create_user
Content-Type: application/json

{
  "firm_name": "Entreprise2",
  "first_name": "Contact2",
  "last_name": "Nom2",
  "email": "contact2@example.com",
  "phone_number": "9876543210",
  "password": "motDePasse2"
}

###
# Créer un nouvel utilisateur
POST http://localhost:3000/users/create_user
Content-Type: application/json

{
  "firm_name": "Entreprise5",
  "first_name": "Contact5",
  "last_name": "Nom5",
  "email": "contact5@example.com",
  "phone_number": "6551234567",
}



###
# Mettre à jour un utilisateur existant
PUT http://localhost:3000/users/update_user/Entreprise5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJtX25hbWUiOiJhZG1pbiIsImlhdCI6MTcwNTkzNDk0MywiZXhwIjoxNzEzNzEwOTQzfQ.mCGQXMr9L-EAprjYGRH_xZ5j_PC8vMrQSVKs5wmdOxM
Content-Type: application/json

{
  "first_name": "Contact5",
  "last_name": "Nom5",
  "email": "benrei@hotmail.fr",
  "phone_number": "1112223333",
  "generate_password": true
}

###
# Supprimer un utilisateur
DELETE http://localhost:3000/users/delete_user/Entreprise2

###
# Obtenir un utilisateur par son nom d'entreprise
GET http://localhost:3000/users/get_user/Entreprise5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJtX25hbWUiOiJhZG1pbiIsImlhdCI6MTcwNTY3MTg3NywiZXhwIjoxNzEzNDQ3ODc3fQ.PMOGNubmucY-FSMsPE4b_AKqcMBjQriinZ8VvMqRAj0

###
# Obtenir la liste de tous les utilisateurs
GET http://localhost:3000/users/get_all_users

###
PUT http://localhost:3000/users/update_user/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJtX25hbWUiOiJhZG1pbiIsImlhdCI6MTcwNTkyMDAzOSwiZXhwIjoxNzEzNjk2MDM5fQ.rAXI6O99hgQMj395zFuFG_FesOURlLL_wW0AguhszBk
Content-Type: application/json

{
  "is_admin" : false
}

###
POST http://localhost:3000/users/notify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJtX25hbWUiOiJhZG1pbiIsImlhdCI6MTcwNTY3NjM2MywiZXhwIjoxNzEzNDUyMzYzfQ.jswgQhW1Cr4uGI4n3kj_nbosNC18LxKjg7GfOSXC_3s
Content-Type: application/json

{
  "firm_name": "Entreprise2"
}

###
GET http://localhost:3000/users/get_all_firm_name
Content-Type: application/json



### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "firm_name": "admin",
    "password": "MDPadmin"
}

### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "firm_name": "Entreprise2",
    "password": "410811"
}

###
POST http://localhost:3000/auth/logout
Content-Type: application/json

###
PUT http://localhost:3000/client/recup_mail?firm_name=Entreprise2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJtX25hbWUiOiJFbnRyZXByaXNlMiIsImlhdCI6MTcwNTkxNDUyNSwiZXhwIjoxNzEzNjkwNTI1fQ.TC8D0XTm0NcwsOQzogjXdn-Z67WUMexMM26EPdlz8DQ
Content-Type: application/json
